name: amd64 arm64-gcc CMake

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install gcc-arch64
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        sudo apt-get install binfmt-support qemu qemu-user-static
    - name: Get Sources
      uses: actions/checkout@v3
    - name: Build and Test
      run: |
        echo $PWD
        wget https://musl.cc/aarch64-linux-musl-cross.tgz
        tar -xvzf aarch64-linux-musl-cross.tgz      
        ./aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc --version
        ls ./aarch64-linux-musl-cross/bin/
        sudo cp -r ./aarch64-linux-musl-cross/aarch64-linux-musl/lib/* /lib/
        ls /lib/
        wget https://gamma.hdfgroup.org/ftp/pub/outgoing/h4map/src/h4map.tar.gz
        tar zxvf h4map.tar.gz
        cd h4map/jpeg-6b
        ./configure CC=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc AR=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar
        make
        sudo make install-lib
        cd ../..
        pwd
        ls
        git clone https://github.com/madler/zlib
        cd zlib
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc -DCMAKE_AR=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar -DCMAKE_SYSTEM_PROCESSOR=arm ..
        make
        sudo make install
        cd ../..
        git clone https://github.com/alisw/libtirpc
        cd libtirpc
        chmod u+x ./autogen.sh
        ./autogen.sh
        ./configure CC=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc AR=home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar
        make
        sudo make install
        cd ..
        pwd
        ls
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc -DCMAKE_AR=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar -DCMAKE_SYSTEM_PROCESSOR=arm -DJPEG_DIR=/usr/local -DHDF4_BUILD_FORTRAN:BOOL=OFF ..        
        make
        make test
